import { describe, test, beforeEach } from "vitest";
import { Board } from "../src/Board";
import { Tetromino } from "../src/Tetromino";
import { expect } from "chai";

function fallToBottom(board){
    for(let i=0; i<16;i++){
        board.tick()
    }
}

function moveToLeftEdge(board){
    for(let i=0; i<16; i++){
        board.moveLeft()
    }
}

function moveToRightEdge(board){
    for(let i=0; i<16;i++){
        board.moveRight()
    }
}

describe("Erasing rows of same type", ()=>{
    let board;
    beforeEach(()=>{
        board = new Board(8,10)
    })

    test("the bottom row gets removed, when its full", ()=>{
        board.drop(Tetromino.I_SHAPE)
       
        moveToLeftEdge(board)
        fallToBottom(board)
        expect(board.toString()).to.equalShape(
           `........
            ........
            ........
            ........
            ........
            ........
            ........
            ........
            ........
            IIII....` 
        )
        board.drop(Tetromino.I_SHAPE)
        moveToRightEdge(board)
        fallToBottom(board)
         expect(board.toString()).to.equalShape(
           `........
            ........
            ........
            ........
            ........
            ........
            ........
            ........
            ........
            ........` 
        )





    })

    test("Multiple rows get removed when full", () =>{
        board.drop(Tetromino.O_SHAPE)
        moveToLeftEdge(board)
        fallToBottom(board)
        board.drop(Tetromino.O_SHAPE)
      
        board.moveLeft()
        fallToBottom(board)
        board.drop(Tetromino.O_SHAPE)
        moveToRightEdge(board)
        fallToBottom(board)
         expect(board.toString()).to.equalShape(
           `........
            ........
            ........
            ........
            ........
            ........
            ........
            ........
            OOOO..OO
            OOOO..OO`)
        board.drop(Tetromino.O_SHAPE)
        board.moveRight()
        fallToBottom(board)
        expect(board.toString()).to.equalShape(
           `........
            ........
            ........
            ........
            ........
            ........
            ........
            ........
            ........
            ........` 
        )

    })

})