
import { describe, test, beforeEach } from "vitest";
import { Board } from "../src/Board";
import { Tetromino } from "../src/Tetromino";
import { expect } from "chai";

function fallToBottom(board) {
  for (let i = 0; i < 19; i++) {
    board.tick();
  }
}

function moveToRightEdge(board){
  for(let i = 0; i<19; i++) {
    board.moveRight();
  }
}
function moveToLeftEdge(board){
  for(let i = 0; i<19; i++) {
    board.moveLeft();
  }
}

describe("Test Rotating I shape", () =>{
    let board;
    beforeEach(()=>{
        board = new Board(15,10);
    })
    
    test("Test Dropping the I shape to a bigger board", ()=>{
      board.drop(Tetromino.I_SHAPE)
      expect(board.toString()).to.equalShape(
        `...............
         ...............
         .....IIII......
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )
        
    })

    test("Test rotating the I shape right", () =>{
      board.drop(Tetromino.I_SHAPE)
      board.rotateRight()
      expect(board.toString()).to.equalShape(
        `.......I.......
         .......I.......
         .......I.......
         .......I.......
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )

      
    })

    test("The I shape can be moved horizontally at the last second", () =>{
      board.drop(Tetromino.I_SHAPE)
      board.rotateRight()
      board.moveDown().moveDown().moveDown().moveDown().moveDown().moveDown()
      board.rotateRight()
      expect(board.toString()).to.equalShape(
        `...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         .....IIII......
         ...............`
      )
    })


    test("I shape cannot be rotated right if too close to wall", () =>{
      board.drop(Tetromino.I_SHAPE)
      board.rotateRight()
      moveToRightEdge(board)
      expect(board.toString()).to.equalShape(
        `..............I
         ..............I
         ..............I
         ..............I
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )
      board.rotateRight()
      expect(board.toString()).to.equalShape(
        `..............I
         ..............I
         ..............I
         ..............I
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )


      
    })
  

})


describe("Test Rotating T shape", () =>{
  let board;
    beforeEach(()=>{
        board = new Board(15,10);
    })
    
    test("Test Dropping the T shape to a bigger board", ()=>{
      board.drop(Tetromino.T_SHAPE)
      expect(board.toString()).to.equalShape(
        `.......T.......
         ......TTT......
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )
        
    })
    test("Test Rotating T shape right", ()=>{
      board.drop(Tetromino.T_SHAPE)
      board.rotateRight()
      expect(board.toString()).to.equalShape(
        `.......T.......
         .......TT......
         .......T.......
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )

      board.rotateRight()

       expect(board.toString()).to.equalShape(
        `...............
         ......TTT......
         .......T.......
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )

     
        
    })


})

describe("Test Rotating O shape, which cannot be rotated", () =>{

  let board;
  beforeEach(()=>{
    board = new Board(15,10)
  })

  test("Test Dropping the T shape to a bigger board", ()=>{
      board.drop(Tetromino.O_SHAPE)
      expect(board.toString()).to.equalShape(
        `.......OO......
         .......OO......
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )

      board.rotateRight()
      expect(board.toString()).to.equalShape(
        `.......OO......
         .......OO......
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )

        
    })


})