
import { describe, test, beforeEach } from "vitest";
import { Board } from "../src/Board";
import { Tetromino } from "../src/Tetromino";
import { expect } from "chai";

function fallToBottom(board) {
  for (let i = 0; i < 19; i++) {
    board.tick();
  }
}

function moveToRightEdge(board){
  for(let i = 0; i<19; i++) {
    board.moveRight();
  }
}
function moveToLeftEdge(board){
  for(let i = 0; i<19; i++) {
    board.moveLeft();
  }
}

describe("Test Rotating I shape", () =>{
    let board;
    beforeEach(()=>{
        board = new Board(15,10);
    })
    
    test("Test Dropping the I shape to a bigger board", ()=>{
      board.drop(Tetromino.I_SHAPE)
      expect(board.toString()).to.equalShape(
        `.....IIII......
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )
        
    })

    test("Test rotating the I shape right", () =>{
      board.drop(Tetromino.I_SHAPE)
      board.rotateRight()
      expect(board.toString()).to.equalShape(
        `.......I.......
         .......I.......
         .......I.......
         .......I.......
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )

      
    })

    test("The I shape can be moved horizontally at the last second", () =>{
      board.drop(Tetromino.I_SHAPE)
      board.rotateRight()
      board.moveDown().moveDown().moveDown().moveDown().moveDown().moveDown()
      board.rotateRight()
      expect(board.toString()).to.equalShape(
        `...............
         ...............
         ...............
         ...............
         ...............
         ...............
         .....IIII......
         ...............
         ...............
         ...............`
      )
    })


    test("I shape will kick if too close to right wall", () =>{
      board.drop(Tetromino.I_SHAPE)
      board.rotateRight()
      moveToRightEdge(board)
      expect(board.toString()).to.equalShape(
        `..............I
         ..............I
         ..............I
         ..............I
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )
      board.rotateRight()
      expect(board.toString()).to.equalShape(
        `...........IIII
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )


      
    })

    test("I shape will kick if too close to left wall", () =>{
      board.drop(Tetromino.I_SHAPE)
      board.rotateRight()
      moveToLeftEdge(board)
      expect(board.toString()).to.equalShape(
        `I..............
         I..............
         I..............
         I..............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )
      board.rotateRight()
      expect(board.toString()).to.equalShape(
        `IIII...........
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )
      

      
    })

    test("The I shape can kick from other I blocks", () =>{
      board.drop(Tetromino.I_SHAPE)
      board.rotateRight()
      fallToBottom(board)

      
      expect(board.fallenBlocksCoordinatesList).to.include.deep.members([
        {row:6, col:7,char:"I"},
        {row:7, col:7,char:"I"},
        {row:8, col:7,char:"I"},
        {row:9, col:7,char:"I"}
      ])

      board.drop(Tetromino.I_SHAPE)
      board.rotateLeft()
      board.moveLeft()
      board.moveDown().moveDown().moveDown().moveDown().moveDown()
      expect(board.getFallingBlocks()).to.include.deep.members([
        {row:5, col:6},
        {row:6, col:6},
        {row:7, col:6},
        {row:8, col:6}
      ])
      expect(board.toString()).to.equalShape(
        `...............
         ...............
         ...............
         ...............
         ...............
         ......I........
         ......II.......
         ......II.......
         ......II.......
         .......I.......`)
      board.tick()
      expect(board.toString()).to.equalShape(
        `...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ......II.......
         ......II.......
         ......II.......
         ......II.......`)
      board.rotateRight()
      /*expect(board.getFallingBlocks()).to.include.deep.members([
        {row:5, col:6},
        {row:6, col:6},
        {row:7, col:6},
        {row:8, col:6}
      ])*/
      expect(board.toString()).to.equalShape(
        `...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...IIIII.......
         .......I.......
         .......I.......
         .......I.......`
      )
      

    })

    test("The I shape can kick right from other I blocks", ()=>{
      board.drop(Tetromino.I_SHAPE)
      board.rotateLeft()
      fallToBottom(board)
      board.drop(Tetromino.I_SHAPE)
      board.rotateLeft()
      board.moveRight()
      board.tick()
      board.tick()
      board.tick()
      board.moveDown()
      board.moveDown()
      board.moveDown()
      expect(board.toString()).to.equalShape(
        `...............
         ...............
         ...............
         ...............
         ...............
         ...............
         .......II......
         .......II......
         .......II......
         .......II......`
        )
        board.rotateLeft()
        expect(board.toString()).to.equalShape(
        `...............
         ...............
         ...............
         ...............
         ...............
         ...............
         .......IIIII...
         .......I.......
         .......I.......
         .......I.......`
        )


    })
    test("The I shape can kick from other blocks", () =>{
      board.drop(Tetromino.O_SHAPE)
      fallToBottom(board)
      board.drop(Tetromino.O_SHAPE)
      fallToBottom(board)
      board.drop(Tetromino.I_SHAPE)
      board.rotateLeft()
      board.moveLeft().moveLeft()
      
      expect(board.toString()).to.equalShape(
        `.....I.........
         .....I.........
         .....I.........
         .....I.........
         ...............
         ...............
         ......OO.......
         ......OO.......
         ......OO.......
         ......OO.......`
      )
      
      board.moveDown().moveDown().moveDown().moveDown().moveDown().moveDown()
      
      expect(board.toString()).to.equalShape(
        `...............
         ...............
         ...............
         ...............
         ...............
         ...............
         .....IOO.......
         .....IOO.......
         .....IOO.......
         .....IOO.......`
      )
      board.rotateRight()
      expect(board.toString()).to.equalShape(
        `...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ..IIIIOO.......
         ......OO.......
         ......OO.......
         ......OO.......`
      )

    })

    test("The I shape can kick upwards from other shapes", () =>{

      board.drop(Tetromino.O_SHAPE)
      fallToBottom(board)
      board.drop(Tetromino.O_SHAPE)
      fallToBottom(board)
      board.drop(Tetromino.O_SHAPE)
      board.moveLeft()
      board.moveLeft()
      fallToBottom(board)
      board.drop(Tetromino.O_SHAPE)
      board.moveLeft()
      board.moveLeft()
      fallToBottom(board)
      board.drop(Tetromino.I_SHAPE)
      board.moveDown()
      board.moveDown()
     
      board.moveDown()
      board.moveDown()
      board.moveDown()
      board.moveDown()
      board.moveLeft()
      board.rotateRight()
      expect(board.toString()).to.equalShape(
        `...............
         ...............
         ......I........
         ......I........
         ......I........
         ......I........
         ....OOOO.......
         ....OOOO.......
         ....OOOO.......
         ....OOOO.......`
      )


    })

    
  

})


describe("Test Rotating T shape", () =>{
  let board;
    beforeEach(()=>{
        board = new Board(15,10);
    })
    
    test("Test Dropping the T shape to a bigger board", ()=>{
      board.drop(Tetromino.T_SHAPE)
      expect(board.toString()).to.equalShape(
        `.....TTT.......
         ......T........
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )
        
    })
    test("Test Rotating T shape right", ()=>{
      board.drop(Tetromino.T_SHAPE)
      board.rotateRight()
      expect(board.toString()).to.equalShape(
        `......T........
         .....TT........
         ......T........
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )

      board.rotateRight()

       expect(board.toString()).to.equalShape(
        `...............
         ......T........
         .....TTT.......
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )

     
        
    })

    test("Test rotating T shape left", () =>{
      board.drop(Tetromino.T_SHAPE)
      board.rotateLeft()
      expect(board.toString()).to.equalShape(
        `......T........
         ......TT.......
         ......T........
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )

    })

    test("T shape wall kicks right wall", () =>{
      board.drop(Tetromino.T_SHAPE)
      board.rotateRight()
      moveToRightEdge(board)
      expect(board.toString()).to.equalShape(
        `..............T
         .............TT
         ..............T
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )
      board.rotateRight()
      expect(board.toString()).to.equalShape(
        `...............
         .............T.
         ............TTT
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )

    })

    test("T shape wall kicks over left wall", ()=>{
      board.drop(Tetromino.T_SHAPE)
      board.rotateLeft()
      moveToLeftEdge(board)
      expect(board.toString()).to.equalShape(
        `T..............
         TT.............
         T..............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )
      board.rotateRight()
      expect(board.toString()).to.equalShape(
        `TTT............
         .T.............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )

    })

    test("T shape will wall kick from other blocks", ()=>{
      board.drop(Tetromino.O_SHAPE)
      fallToBottom(board)
      board.drop(Tetromino.O_SHAPE)
      fallToBottom(board)
      board.drop(Tetromino.T_SHAPE)
      board.rotateRight()
      board.moveLeft()
   

      board.moveDown()
      board.moveDown()
      board.moveDown()
      board.moveDown()
      board.moveDown()
      board.moveDown()
      expect(board.toString()).to.equalShape(
        `...............
         ...............
         ...............
         ...............
         ...............
         ...............
         .....TOO.......
         ....TTOO.......
         .....TOO.......
         ......OO.......`
      )
      board.rotateLeft()
      expect(board.toString()).to.equalShape(
        `...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...TTTOO.......
         ....T.OO.......
         ......OO.......
         ......OO.......`
      )
      

    })

    test("T shape wall kicks left from other T shapes", () =>{
      board.drop(Tetromino.T_SHAPE)
      fallToBottom(board)
      board.drop(Tetromino.T_SHAPE)
      board.rotateLeft()
      board.moveLeft()
      fallToBottom(board)
      expect(board.toString()).to.equalShape(
        `...............
         ...............
         ...............
         ...............
         ...............
         .....T.........
         .....TT........
         .....T.........
         .....TTT.......
         ......T........`
      )
      board.drop(Tetromino.T_SHAPE)
      board.rotateRight()
      board.moveLeft()
      board.moveLeft()
      board.moveDown()
      board.moveDown()
      board.moveDown()
      board.moveDown()
      board.moveDown()
      expect(board.toString()).to.equalShape(
        `...............
         ...............
         ...............
         ...............
         ...............
         ....TT.........
         ...TTTT........
         ....TT.........
         .....TTT.......
         ......T........`
      )
      board.rotateRight()
      expect(board.toString()).to.equalShape(
        `...............
         ...............
         ...............
         ...............
         ...............
         .....T.........
         ...T.TT........
         ..TTTT.........
         .....TTT.......
         ......T........`
      )
      


      //board.
    })

    test("The T shape kicks up from other T shapes and from other shapes", () =>{
      board.drop(Tetromino.T_SHAPE)
      fallToBottom(board)
      board.drop(Tetromino.T_SHAPE)
      board.moveLeft()
      board.moveLeft()
      board.moveLeft()
      board.moveLeft()
      fallToBottom(board)
      expect(board.toString()).to.equalShape(
        `...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         .TTT.TTT.......
         ..T...T........`
      )
      
      
      



    })




})

describe("Test Rotating O shape, which cannot be rotated", () =>{

  let board;
  beforeEach(()=>{
    board = new Board(15,10)
  })

  test("Test Dropping the T shape to a bigger board", ()=>{
      board.drop(Tetromino.O_SHAPE)
      expect(board.toString()).to.equalShape(
        `......OO.......
         ......OO.......
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )

      board.rotateRight()
      expect(board.toString()).to.equalShape(
        `......OO.......
         ......OO.......
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............
         ...............`
      )

        
    })


})